// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCore.DynamicOrderBy.Demo.Models
{
    public partial class TTest
    {
        public int Id { get; set; }
        public int? SortIndex { get; set; }
        public DateTime? CreateTime { get; set; }
        public string Abc { get; set; }
    }
}